spring.application.name=OnlineDoctorsClinic

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/doctors_clinic
spring.datasource.username=root
spring.datasource.password=root123


# JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080

logging.level.org.springframework.web=DEBUG